# Copyright 2023 The ChromiumOS Authors
# Distributed under the terms of the GNU General Public License v2
#
# Board kernel override for the T2 Mac board.
#
# This is a verbatim copy of the upstream ebuild
#
#     chromiumos-overlay/sys-kernel/chromeos-kernel-6_1/
#         chromeos-kernel-6_1-6.1.25-r227.ebuild
#
# with ONLY the revision bumped (r227 -> r228). The kernel source, commit and
# branch are unchanged -- this override exists purely to raise the revision so
# portage selects *this* ebuild, which makes FILESDIR resolve to
#
#     overlay-amd64-openfyde_iris-t2/sys-kernel/chromeos-kernel-6_1/files/
#
# cros-kernel2.eclass then picks the T2 patches up automatically:
#
#     apply_private_patches() {
#         local patches=( "${FILESDIR}"/*.patch )
#         [[ ${#patches[@]} -gt 0 ]] && eapply "${patches[@]}"
#     }
#
#     cros-kernel2_src_prepare() {
#         if [[ "${PV}" != "9999" ]] || use apply_patches; then
#             apply_private_patches
#         fi
#     }
#
# Without this ebuild the files/*.patch in this directory would never be read:
# portage only reads the FILESDIR of the package directory containing the
# *selected* ebuild, and upstream's copy in chromiumos-overlay has no patches.
#
# When upstream bumps chromeos-kernel-6_1, re-copy its ebuild here, keep the
# same bump-by-one revision, and re-check that files/*.patch still apply.
# ---------------------------------------------------------------------------

EAPI=7

CROS_WORKON_COMMIT="6a8a0d280f118a3f901ed2976255fef57b8261ba"
CROS_WORKON_TREE="0cf3cec77dc9428c29e7943078cd2ea89ab37cc3"
CROS_WORKON_PROJECT="chromiumos/third_party/kernel"
CROS_WORKON_LOCALNAME="kernel/v6.1"
CROS_WORKON_EGIT_BRANCH="chromeos-6.1"

# AFDO_PROFILE_VERSION is the build on which the profile is collected.
# This is required by kernel_afdo.
# ARM_AFDO_PROFILE_VERSION is an alternative profile which is going to be
# applied with the flag kern_arm_afdo.
#
# TODO: Allow different versions for different CHROMEOS_KERNEL_SPLITCONFIGs

# By default, let cros-kernel2 define AFDO_LOCATION.  This is used in the
# kernel AFDO verify jobs to specify the location.
AFDO_LOCATION=""

# Auto-generated by PFQ, don't modify.
AFDO_PROFILE_VERSION=""
ARM_AFDO_PROFILE_VERSION="R110-15263.0-1670236325"

# Set AFDO_FROZEN_PROFILE_VERSION to freeze the afdo profiles.
# If non-empty, it overrides the value set by AFDO_PROFILE_VERSION.
# Note: Run "ebuild-<board> /path/to/ebuild manifest" afterwards to create new
# Manifest file.
AFDO_FROZEN_PROFILE_VERSION=""
ARM_AFDO_FROZEN_PROFILE_VERSION=""

# This must be inherited *after* EGIT/CROS_WORKON variables defined
inherit cros-workon cros-kernel2

HOMEPAGE="https://www.chromium.org/chromium-os/chromiumos-design-docs/chromium-os-kernel"
DESCRIPTION="Chrome OS Linux Kernel 6.1"
KEYWORDS="*"

# Update files/revision_bump file when you change "cros-kernel2.eclass" to work
# around https://issuetracker.google.com/201299127.
#
# NB: The exact file content does not matter.  It just needs to be different
# from whatever is in there currently.
#
# Don't forget to update the file for _all_ chromeos-kernel cros-workon packages.
